"""add_visible_column_to_agent_message

Revision ID: 2fd970a82e95
Revises: 443c1e27f7a7
Create Date: 2025-04-10 20:55:40.624687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fd970a82e95'
down_revision: Union[str, None] = '443c1e27f7a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_messages', sa.Column('visible', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_messages', 'visible')
    # ### end Alembic commands ###
